global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'fastapi'
    metrics_path: /metrics
    static_configs:
      - targets: ['recsys-api:3010']

  - job_name: 'frontend'
    metrics_path: /metrics
    static_configs:
      - targets: ['frontend:5173']

  - job_name: 'mlflow'
    metrics_path: /metrics
    static_configs:
      - targets: ['mlflow:5000']

  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']
